# Generated by Django 5.1.1 on 2024-10-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('municipios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contribuinte', models.CharField(max_length=200)),
                ('tipo_pessoa', models.CharField(choices=[('FÍSICA', 'FÍSICA'), ('JURÍDICA', 'JURÍDICA')], max_length=50)),
                ('documento', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=11)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('localidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_contri', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('origem', models.CharField(blank=True, default='usuário', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFinalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_finalidade', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ope_aval', models.CharField(max_length=40)),
                ('calculo_operacao_aval', models.CharField(blank=True, choices=[('sobre diferença', 'sobre diferença'), ('sobre maior valor', 'sobre maior valor'), ('sobre valor declarado', 'sobre valor declarado')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('sequencial', models.IntegerField(blank=True, default=1, null=True)),
                ('data_andamento', models.DateField()),
                ('situacao_pagamento', models.CharField(blank=True, choices=[('Sem Pagamento', 'Sem Pagamento'), ('Com Pagamento', 'Com Pagamento'), ('Registrado no andamento "Avaliação Imobiliária"', 'Registrado no andamento "Avaliação Imobiliária"')], max_length=200, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('numero_aiti', models.CharField(blank=True, max_length=10, null=True)),
                ('data_aiti', models.DateField(blank=True, null=True)),
                ('dias_data_prazo', models.IntegerField(blank=True, null=True)),
                ('data_prazo', models.DateField(blank=True, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, max_length=2000, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivo/')),
                ('arquivo2', models.FileField(blank=True, null=True, upload_to='arquivo/')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('localizacao_processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_de_processos.localizacaoprocesso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArquivoAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('arquivo', models.FileField(upload_to='arquivo/')),
                ('andamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamento_upload', to='controle_de_processos.andamento')),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('numero', models.CharField(max_length=10, verbose_name='N°')),
                ('uf', models.CharField(choices=[('MS', 'MS')], default='MS', max_length=2)),
                ('data_div_ativa', models.DateField(blank=True, null=True)),
                ('valor_tributo', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_atualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('data_valor_atualizado', models.DateField(blank=True, null=True)),
                ('exercicio', models.IntegerField()),
                ('contribuinte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_de_processos.contribuinte')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipios.municipio')),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='andamento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_de_processos.processo'),
        ),
        migrations.CreateModel(
            name='TipoAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_andamento', models.CharField(max_length=100, verbose_name='Tipo de Andamento')),
                ('status', models.CharField(choices=[('Executado', 'Executado'), ('Recebido', 'Recebido'), ('Encerrado', 'Encerrado'), ('Em Andamento', 'Em Andamento'), ('Suspenso', 'Suspenso')], max_length=20)),
                ('prazo', models.BooleanField(default=False)),
                ('pagamento', models.BooleanField(default=False)),
                ('encaminhamento', models.BooleanField(default=False)),
                ('numero_aiti', models.BooleanField(default=False)),
                ('avaliacao_imobiliaria', models.BooleanField(default=False)),
                ('criar_atendimento', models.BooleanField(default=False)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='andamento',
            name='tipo_andamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_de_processos.tipoandamento'),
        ),
        migrations.CreateModel(
            name='TipoAndamentoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('tipo_and_aval', models.CharField(max_length=100)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('sequencial', models.IntegerField(blank=True, default=1, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_avaliado', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_itbi_diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('valor_pago_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('data_valor_pago', models.DateField(blank=True, null=True)),
                ('andamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controle_de_processos.andamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario')),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_andamento_avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_de_processos.tipoandamentoavaliacao')),
                ('finalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_de_processos.tipofinalidade')),
                ('operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_de_processos.tipooperacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_de_processos.tipoprocesso'),
        ),
    ]
