# Generated by Django 5.1.1 on 2024-10-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('origem', models.CharField(blank=True, default='usuario', max_length=20, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('Assessoria', 'Assessoria'), ('Sistema', 'Sistema')], max_length=100, null=True)),
                ('contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
