# Generated by Django 5.1.1 on 2024-10-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAndamentoDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_id', models.PositiveIntegerField()),
                ('tipo_objeto', models.CharField(max_length=255)),
                ('view', models.CharField(max_length=255)),
                ('acao', models.CharField(max_length=255)),
                ('processo', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('andamento', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_hora',),
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProcessoDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_id', models.PositiveIntegerField()),
                ('tipo_objeto', models.CharField(max_length=255)),
                ('view', models.CharField(max_length=255)),
                ('acao', models.CharField(max_length=255)),
                ('processo', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_hora',),
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProcessoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_id', models.PositiveIntegerField()),
                ('tipo_objeto', models.CharField(max_length=255)),
                ('view', models.CharField(max_length=255)),
                ('acao', models.CharField(max_length=255)),
                ('numero_antigo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_novo', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_hora',),
            },
        ),
    ]
