# Generated by Django 5.1.1 on 2024-10-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafico.ano')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafico.receita')),
            ],
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeiro', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fevereiro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('marco', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('abril', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('maio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('junho', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('julho', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('agosto', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('setembro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('outubro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('novembro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('dezembro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafico.ficha')),
            ],
        ),
    ]
