# Generated by Django 5.1.1 on 2024-10-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meses',
            new_name='Mes',
        ),
    ]
