# Generated by Django 5.1.1 on 2024-10-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0002_rename_meses_mes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mes',
            new_name='ValorMes',
        ),
    ]
