# Generated by Django 5.1.1 on 2024-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0003_rename_mes_valormes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ano',
            name='nome',
        ),
        migrations.AddField(
            model_name='ano',
            name='valor',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
