# Generated by Django 5.1.1 on 2024-11-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0004_remove_ano_nome_ano_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ano',
            name='valor',
        ),
        migrations.AddField(
            model_name='ano',
            name='nome',
            field=models.CharField(default='2017', max_length=4),
            preserve_default=False,
        ),
    ]
